'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MlbEdit.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Aegean() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Aegean", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property ideogramChecker() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ideogramChecker", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a 00010000
        '''a2 00010040
        '''ai 00010041
        '''au 00010042
        '''e 00010001
        '''i 00010002
        '''o 00010003
        '''u 00010004
        '''da 00010005
        '''de 00010006
        '''di 00010007
        '''do 00010008
        '''du 00010009
        '''dwe 00010043
        '''dwo 00010044
        '''ja 0001000A
        '''je 0001000B
        '''jo 0001000D
        '''ka 0001000F
        '''ke 00010010
        '''ki 00010011
        '''ko 00010012
        '''ku 00010013
        '''ma 00010014
        '''me 00010015
        '''mi 00010016
        '''mo 00010017
        '''mu 00010018
        '''na 00010019
        '''ne 0001001A
        '''ni 0001001B
        '''no 0001001C
        '''nu 0001001D
        '''nwa 00010045
        '''pa 0001001E
        '''pe 0001001F
        '''pi 00010020
        '''po 00010021
        '''pu 00010022
        '''pu2 000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MlbDictionary() As String
            Get
                Return ResourceManager.GetString("MlbDictionary", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
